---
abstract: "fairly experimental parser for HTML 'microdata'"
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
keywords:
  - RDF
  - Trine
  - Microdata
  - 'Semantic Web'
  - HTML
  - HTML5
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-HTML5-Microdata-Parser
no_index:
  directory:
    - inc
    - t
requires:
  Encode: 0
  HTML::HTML5::Parser: 0.100
  HTML::HTML5::Sanity: 0.100
  RDF::Trine: 0.112
  URI::Escape: 0
  URI::URL: 0
  XML::LibXML: 1.60
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=HTML-HTML5-Microdata-Parser
  homepage: http://search.cpan.org/dist/HTML-HTML5-Microdata-Parser/
  license: http://dev.perl.org/licenses/
  repository: http://goddamn.co.uk/viewvc/perlmods/HTML-HTML5-Microdata-Parser/
version: 0.031
